name: Patch target vbmeta

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download AVB tool
        run: |
          git clone https://android.googlesource.com/platform/external/avb

      - name: Patch vbmeta
        run: |
          python3 avb/avbtool.py erase_footer --image vbmeta.img || true
          cp vbmeta.img vbmeta_patched.img

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: vbmeta_patched
          path: vbmeta_patched.img

      - name: Make a Release
        uses: ncipollo/release-action@v1
        with:
          tag: run-${{ github.run_number }}
          name: patched vbmeta
          artifacts: vbmeta_patched.img
          prerelease: true