name: Patch target vbmeta

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clone AVBtool from source
        run: |
          git clone https://android.googlesource.com/platform/external/avb

      - name: Patch Target vbmeta
        run: |
          python3 avb/avbtool.py extract_vbmeta_image --image vbmeta.img --output extracted/vbmeta_extracted.img
          python3 avb/avbtool.py make_vbmeta_image \
            --flags 2 \
            --include_descriptors_from_image vbmeta.img \
            --output vbmeta_patched.img

      - name: Verify if vbmeta has been patched successfully
        run: |
          python3 avb/avbtool.py info_image --image vbmeta_patched.img | tee vbinfo.txt
          if grep -q "Flags:[[:space:]]*2" vbinfo.txt; then
            echo "vbmeta: successfully patched"
          else
            echo "vbmeta: patch failed"
            exit 1
          fi

      - name: Upload to releases
        uses: actions/upload-artifact@v4
        with:
          name: vbmeta_patched
          path: vbmeta_patched.img

      - name: Create releases
        uses: ncipollo/release-action@v1
        with:
          tag: run-${{ github.run_number }}
          name: patched vbmeta
          artifacts: vbmeta_patched.img
          prerelease: true