name: Patch target vbmeta

on:
  workflow_dispatch:
    inputs:
      codename:
        description: Choose device
        required: true
        type: choice
        options:
          - e1s  (Galaxy S24) (Exynos)
          - a26x (Galaxy A26)   
          - a35x (Galaxy A35)

permissions:
  contents: write

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clone AVBtool from source
        run: |
          git clone https://android.googlesource.com/platform/external/avb

      - name: Patch Target vbmeta
        run: python3 avb/avbtool.py make_vbmeta_image --flags 2 --include_descriptors_from_image target/${{ github.event.inputs.codename }}/vbmeta.img --output target/${{ github.event.inputs.codename }}/vbmeta_patched.img

      - name: Verify if vbmeta has been patched successfully
        run: |
          python3 avb/avbtool.py info_image --image target/${{ github.event.inputs.codename }}/vbmeta_patched.img | tee target/${{ github.event.inputs.codename }}/vbinfo.txt
          grep -q "Flags:[[:space:]]*2" target/${{ github.event.inputs.codename }}/vbinfo.txt || { echo "patch failed"; exit 1; }
          tfingerprint=$(grep "fingerprint" target/${{ github.event.inputs.codename }}/vbinfo.txt | awk -F"'" '{print $2}')
          if [ "$tfingerprint" ]; then
            CODENAME=$(echo $tfingerprint | cut -d'/' -f3 | cut -d':' -f1)
            echo "codename=$CODENAME" >> $GITHUB_ENV
          else
            echo "codename=unknown" >> $GITHUB_ENV
          fi

      - name: Upload to releases
        uses: actions/upload-artifact@v4
        with:
          name: vbmeta_patched_${{ github.event.inputs.codename }}
          path: target/${{ github.event.inputs.codename }}/vbmeta_patched.img

      - name: Create releases
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.codename }}
          name: run-${{ github.run_number }}
          artifacts: target/${{ github.event.inputs.codename }}/vbmeta_patched.img
          prerelease: true